# Generated by Django 5.0.2 on 2024-02-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_amount_product_quantity_purchase_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity_of_product',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
