# Generated by Django 5.0.2 on 2024-03-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_purchase_quantity_of_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
