# Generated by Django 5.0.2 on 2024-03-10 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_purchase_created_at_alter_return_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 10, 12, 0, 3, 385163, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='return',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 10, 12, 0, 3, 385163, tzinfo=datetime.timezone.utc)),
        ),
    ]
